version: "3.3"

services:
  dermatitis_frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    container_name: dermatitis_frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - dermatitis_network
    volumes:
      - ./uploads:/app/public

  dermatitis_backend:
    build: ./backend
    container_name: dermatitis_backend
    restart: unless-stopped
    ports:
      - 8081:8000
    networks:
      - dermatitis_network
    volumes:
      - ./uploads:/app/public

networks:
  dermatitis_network:
    driver: bridge
